name: GitHub Actions Demo
on: [push]
jobs:
  run-python-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.8, 3.9]    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
      - name: run main.py
        run: python main.py
      - name: get python version
        run: python --version
